---
name: Trivy Security Scan

on:
  push:
    branches: "main"
  pull_request:
    branches: "main"
  schedule:
    - cron: '22 20 * * 3'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  scan:
    permissions:
      contents: read  # for actions/checkout to fetch code
      security-events: write  # for github/codeql-action/upload-sarif to upload SARIF results
      actions: read  # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status
    name: Scan
    runs-on: ubuntu-latest
    environment: docker
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Log in to Docker Hardened Hub
        uses: docker/login-action@v3
        with:
          registry: dhi.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Check if Dockerfile exists
        id: dockerfile_check
        run: |
          if [ -f "Dockerfile" ]; then
            echo "exists=true" >> $GITHUB_OUTPUT
          else
            echo "exists=false" >> $GITHUB_OUTPUT
          fi

      - name: Build Docker image
        if: github.event_name != 'schedule'
        run: |
          docker build -f Dockerfile39 -t ${{ github.actor }}/${{ github.event.repository.name }}:39 .
          docker build -f Dockerfile310 -t ${{ github.actor }}/${{ github.event.repository.name }}:310 .
          docker build -f Dockerfile311 -t ${{ github.actor }}/${{ github.event.repository.name }}:311 .
          docker build -f Dockerfile312 -t ${{ github.actor }}/${{ github.event.repository.name }}:312 .
          docker build -f Dockerfile313 -t ${{ github.actor }}/${{ github.event.repository.name }}:313 .
          docker build -f Dockerfile314 -t ${{ github.actor }}/${{ github.event.repository.name }}:314 .


      - name: Run Trivy vulnerability scanner for Docker image
        uses: aquasecurity/trivy-action@0.33.1
        with:
          image-ref: '${{ github.actor }}/${{ github.event.repository.name }}:39'
          format: 'template'
          template: '@/contrib/sarif.tpl'
          output: 'trivy-results-39.sarif'
          scanners: 'vuln,secret,misconfig,license'
          severity: 'CRITICAL,HIGH'

      - name: Run Trivy vulnerability scanner for Docker image
        uses: aquasecurity/trivy-action@0.33.1
        with:
          image-ref: '${{ github.actor }}/${{ github.event.repository.name }}:39'
          format: 'template'
          template: '@/contrib/sarif.tpl'
          output: 'trivy-results-310.sarif'
          scanners: 'vuln,secret,misconfig,license'
          severity: 'CRITICAL,HIGH'

      - name: Run Trivy vulnerability scanner for Docker image
        uses: aquasecurity/trivy-action@0.33.1
        with:
          image-ref: '${{ github.actor }}/${{ github.event.repository.name }}:39'
          format: 'template'
          template: '@/contrib/sarif.tpl'
          output: 'trivy-results-311.sarif'
          scanners: 'vuln,secret,misconfig,license'
          severity: 'CRITICAL,HIGH'

      - name: Run Trivy vulnerability scanner for Docker image
        uses: aquasecurity/trivy-action@0.33.1
        with:
          image-ref: '${{ github.actor }}/${{ github.event.repository.name }}:39'
          format: 'template'
          template: '@/contrib/sarif.tpl'
          output: 'trivy-results-312.sarif'
          scanners: 'vuln,secret,misconfig,license'
          severity: 'CRITICAL,HIGH'

      - name: Run Trivy vulnerability scanner for Docker image
        uses: aquasecurity/trivy-action@0.33.1
        with:
          image-ref: '${{ github.actor }}/${{ github.event.repository.name }}:39'
          format: 'template'
          template: '@/contrib/sarif.tpl'
          output: 'trivy-results-313.sarif'
          scanners: 'vuln,secret,misconfig,license'
          severity: 'CRITICAL,HIGH'

      - name: Run Trivy vulnerability scanner for Docker image
        uses: aquasecurity/trivy-action@0.33.1
        with:
          image-ref: '${{ github.actor }}/${{ github.event.repository.name }}:39'
          format: 'template'
          template: '@/contrib/sarif.tpl'
          output: 'trivy-results-314.sarif'
          scanners: 'vuln,secret,misconfig,license'
          severity: 'CRITICAL,HIGH'

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v4
        with:
          sarif_file: 'trivy-results-39.sarif'
          category: 'python-3.9'

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v4
        with:
          sarif_file: 'trivy-results-310.sarif'
          category: 'python-3.10'

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v4
        with:
          sarif_file: 'trivy-results-311.sarif'
          category: 'python-3.11'

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v4
        with:
          sarif_file: 'trivy-results-312.sarif'
          category: 'python-3.12'

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v4
        with:
          sarif_file: 'trivy-results-313.sarif'
          category: 'python-3.13'

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v4
        with:
          sarif_file: 'trivy-results-314.sarif'
          category: 'python-3.14'
